[tool.poetry]
name = "mr-coin"
version = "0.1.0"
description = ""
authors = ["Rem."]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiogram = "^3.3.0"
flake8 = "^7.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
